// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reputaly.API.Infrastructure.Persistence;

#nullable disable

namespace Reputaly.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reputaly.API.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AiAnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AiDecision")
                        .HasColumnType("text");

                    b.Property<string>("AiDecisionReason")
                        .HasColumnType("text");

                    b.Property<string>("AiSuggestedReply")
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AutoReplied")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedLanguage")
                        .HasColumnType("text");

                    b.Property<string[]>("DetectedTopics")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalReply")
                        .HasColumnType("text");

                    b.Property<string>("GoogleReviewId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SentimentScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "GoogleReviewId")
                        .IsUnique();

                    b.HasIndex("TenantId", "LocationId", "Status");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Reputaly.API.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClerkOrganizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vertical")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Reputaly.API.Domain.TenantLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("GoogleAccountEmail")
                        .HasColumnType("text");

                    b.Property<string>("GoogleLocationId")
                        .HasColumnType("text");

                    b.Property<string>("GoogleRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GoogleTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseLanguage")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantLocations", (string)null);
                });

            modelBuilder.Entity("Reputaly.API.Domain.TenantSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("AiConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("AutoDetectLanguage")
                        .HasColumnType("boolean");

                    b.Property<int>("AutoReplyMinRating")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultResponseLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EscalateIfNoReplyHours")
                        .HasColumnType("integer");

                    b.Property<string[]>("EscalateOnKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("NotificationEmail")
                        .HasColumnType("text");

                    b.HasKey("TenantId");

                    b.ToTable("TenantSettings", (string)null);
                });

            modelBuilder.Entity("Reputaly.API.Domain.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantUsers", (string)null);
                });

            modelBuilder.Entity("Reputaly.API.Domain.Review", b =>
                {
                    b.HasOne("Reputaly.API.Domain.TenantLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reputaly.API.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Reputaly.API.Domain.TenantLocation", b =>
                {
                    b.HasOne("Reputaly.API.Domain.Tenant", "Tenant")
                        .WithMany("Locations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Reputaly.API.Domain.TenantSettings", b =>
                {
                    b.HasOne("Reputaly.API.Domain.Tenant", "Tenant")
                        .WithOne("Settings")
                        .HasForeignKey("Reputaly.API.Domain.TenantSettings", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Reputaly.API.Domain.TenantUser", b =>
                {
                    b.HasOne("Reputaly.API.Domain.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Reputaly.API.Domain.Tenant", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Settings");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
